# Generated by Django 3.2.19 on 2023-06-22 21:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230622_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='exit', max_length=2),
            preserve_default=False,
        ),
    ]
