# Generated by Django 3.2.19 on 2023-06-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_catergory_name_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
